const imageLocation = "";
const ProjectsData = [
        {'name': 'Esri Polymer',
        'relation' : 'An open source project I worked on at Esri UK',
        'snippet': 'A set of Esri mapping web components for Polymer v1.',
        'imageUrl': imageLocation + 'esripolymer.png',
        'technologies': 'JavaScript, Polymer 1.0, ArcGIS JavaScript API',
        'demo' : "",
        'license': "https://raw.githubusercontent.com/EsriUK/esri-polymer/master/LICENSE.txt",
        'github' : "https://github.com/EsriUK/esri-polymer",
        'tags' : ['javascript', 'js', 'css', 'html', 'polymer', 'polymer 1.0', 'maps', 'web components', 'javascript']},

        {'name': 'Harvest',
        'snippet': 'A 3D space themed platform game built using Three.js.',
        'relation' : 'Developer',
        'imageUrl': imageLocation + 'harvest.png',
        'technologies': 'JavaScript, Three.js, jQuery',
        'demo' : "http://www.loxodrome.io/Harvest/index.html",
        'license': "https://raw.githubusercontent.com/JamesMilnerUK/Harvest/master/LICENSE.md",
        'github' : "https://github.com/JamesMilnerUK/Harvest",
        'tags' : ['javascript', 'js', 'css', 'html', 'threejs', 'three.js', 'game', 'jquery', 'three']},

        {'name': 'Lacuna',
        'snippet': 'Lacuna is a 3D Web GIS constructed using Three.js. The web app allows users to store, retrieve, and to a degree analyse and edit 3D geospatial data.',
        'relation' : 'Developer, for my UCL masters thesis',
        'imageUrl': imageLocation + 'lacuna.png',
        'technologies': 'JavaScript, Three.js, jQuery, PHP, PostgreSQL/PostGIS',
        'demo' : "",
        'license': "https://raw.githubusercontent.com/JamesMilnerUK/Lacuna/master/LICENSE.txt",
        'github' : "https://github.com/JamesMilnerUK/Lacuna",
        'tags' : ['javascript', 'js', 'css', 'html', 'threejs', 'three.js', 'gis', 'web', 'maps', 'webgl', 'three', '3d']},

        {'name': 'Hello Live Reload',
        'snippet': 'After struggling to find a easy to follow gulp-livereload example I created this boilerplate.',
        'relation' : 'Developer',
        'imageUrl': imageLocation + 'livereload.png',
        'technologies': 'Gulp, Live Reload',
        'demo' : "",
        'license': "https://raw.githubusercontent.com/JamesMilnerUK/hello-live-reload/master/LICENSE",
        'github' : "https://github.com/JamesMilnerUK/hello-live-reload",
        'tags' : ['javascript', 'gulp', 'livereload', 'task runner', 'nodejs', 'npm', 'tools']},

        {'name': 'On My Way',
        'snippet': 'A Twilio powered app for letting your friends know when you are going to get to them.',
        'relation' : 'An open source project I worked on at Esri UK',
        'imageUrl': imageLocation + 'onmyway.png',
        'technologies': 'HTML, JavaScript, Dojo, PHP, Twilio',
        'demo' : "",
        'license': "https://github.com/EsriUK/on-my-way",
        'github' : "https://github.com/EsriUK/on-my-way",
        'tags' : ['javascript', 'php', 'dojo', 'twilio', 'html', 'frontend', 'api']},

        {'name': 'Loxo',
        'snippet': 'A queryable GeoJSON API powered by MongoDB. Loxo tries to value simplicity and ease of use over covering every use case.',
        'relation' : 'Developer',
        'imageUrl': imageLocation + 'loxo.png',
        'technologies': 'HTML, JavaScript, Loxo, API, Python, Flask, MongoDB',
        'demo' : "",
        'license': "https://github.com/JamesMilnerUK/Loxo/blob/master/LICENSE.txt",
        'github' : "https://github.com/JamesMilnerUK/Loxo",
        'tags' : ['html', 'javascript', 'loxo', 'api', 'python', 'flask', 'mongodb']},

        {'name': 'AR-Carbon Map',
        'relation' : 'Developer, on behalf of AR Carbon at the OS Geovation Hub',
        'snippet': 'A web mapping application that allows farmers to use trade their land into carbon offsetting schemes.',
        'imageUrl': imageLocation + 'arcarbon.png',
        'technologies': 'HTML, JavaScript, PHP, jQuery, WordPress',
        'demo' : "",
        'license': "https://github.com/JamesMilnerUK/AR-Carbon/blob/master/LICENSE.txt",
        'github' : "https://github.com/JamesMilnerUK/AR-Carbon",
        'tags' : ['html', 'wordpress', 'php', 'javascript', 'jquery']},

        {'name': 'External Perimeter Script',
        'relation' : 'Developer, on behalf of Carbon Cooperative at the OS Geovation Hub',
        'snippet': 'A QGIS script for calculating the external facing perimeter of building data in polyline format.',
        'imageUrl': imageLocation + 'qgis.png',
        'technologies': 'QGIS, Python, Processing',
        'demo' : "",
        'license': "https://raw.githubusercontent.com/JamesMilnerUK/qgis-externalperimeter/master/LICENSE.txt",
        'github' : "https://github.com/JamesMilnerUK/qgis-externalperimeter",
        'tags' : ['QGIS', 'Python']},

        {'name': 'Map to PPT',
        'relation' : 'Developer, as part of a hackathon with Map Action',
        'snippet': 'A ArcPy script to convert maps and data driven documents to PowerPoint documents for use in Map Action\'s work out in the field.',
        'imageUrl': imageLocation + 'maptoppt.png',
        'technologies': 'ArcPy, Python',
        'demo' : "",
        'license': "https://raw.githubusercontent.com/JamesMilnerUK/qgis-externalperimeter/master/LICENSE.txt",
        'github' : "https://github.com/JamesMilnerUK/qgis-externalperimeter",
        'tags' : ['arcgis', 'arcmap', 'arcpy', 'data', 'python']},

        {'name': 'Point in Polygon (Go)',
        'relation' : 'Developer',
        'snippet': 'A Point in Polygon program implemented in Go. Also supports a parallel version.',
        'imageUrl': imageLocation + 'pip.png',
        'technologies': 'Go',
        'demo' : "",
        'license': "https://raw.githubusercontent.com/JamesMilnerUK/pip-go/master/LICENSE.txt",
        'github' : "https://github.com/JamesMilnerUK/pip-go",
        'tags' : ['go', 'gis', 'geometry','parallel']},


        {'name': 'Quadtree (Go)',
        'relation' : 'Developer',
        'snippet': 'A Quadtree implementation in Go',
        'imageUrl': imageLocation + 'qt.png',
        'technologies': 'Go',
        'demo' : "",
        'license': "https://raw.githubusercontent.com/JamesMilnerUK/quadtree-go/master/LICENSE.txt",
        'github' : "https://github.com/JamesMilnerUK/quadtree-go",
        'tags' : ['go', 'gis', 'geometry','quadtree', 'indexing','index','spatial']},

        {'name': 'PodCloud Proof of Concept',
        'relation' : 'Developer',
        'snippet': 'A proof of concept app built on behalf of Insight Imaging. PodCloud is a web platform for organising small area drone surveys.',
        'imageUrl': imageLocation + 'podcloud.png',
        'technologies': 'Angular, Firebase',
        'demo' : "",
        'license': "",
        'github' : "",
        'tags' : ['angular', 'javascript', 'firebase','material', 'serverless']},

        {'name': 'Refill',
        'relation' : 'Developer',
        'snippet': 'A Minimum Viable Product crossplatform mobile app built on behalf of Refillable Cities. The app allows you to find nearby places to refill your water bottle for free.',
        'imageUrl': imageLocation + 'refill.png',
        'technologies': 'Angular, Ionic, Firebase',
        'demo' : "",
        'license': "",
        'github' : "",
        'tags' : ['angular', 'javascript', 'firebase','material', 'serverless', 'ionic', 'mobile', 'crossplatform']},

        {'name': 'OS Components',
        'relation' : 'Developer',
        'snippet': 'A maps and geocoder web components built using Polymer',
        'imageUrl': imageLocation + 'components.png',
        'technologies': 'Polymer, Web Components, Ordnance Survey APIs',
        'demo' : "",
        'license': "",
        'github' : "",
        'tags' : ['os', 'ordnance', 'gis', 'web', 'map','components','webcomponents','polymer']},

        {'name': 'Lee Algorithm (JavaScript)',
        'relation' : 'Developer',
        'snippet': 'An implementation of the Lee Algorithm in JavaScript',
        'imageUrl': imageLocation + 'lee.png',
        'technologies': 'JavaScript, HTML, CSS',
        'demo' : "https://jamesmilneruk.github.io/lee-algorithm-js/",
        'license': "https://github.com/JamesMilnerUK/lee-algorithm-js/blob/master/LICENSE",
        'github' : "https://github.com/JamesMilnerUK/lee-algorithm-js",
        'tags' : ['lee', 'algorithm', 'javascript', 'js', 'maze', 'pathfinding']},

        {'name': 'Git Going',
        'relation' : 'Developer',
        'snippet': 'A searchable selection of git commands, using Vue.js',
        'imageUrl': imageLocation + 'gitgoing.png',
        'technologies': 'JavaScript, HTML, CSS',
        'demo' : "https://jamesmilneruk.github.io/git-going/",
        'license': "https://github.com/JamesMilnerUK/git-going/blob/master/LICENSE",
        'github' : "https://github.com/JamesMilnerUK/git-going",
        'tags' : ['vuejs', 'vue-js', 'vue', 'vue.js', 'javascript', 'git']},

        {'name': 'Three.js FPS Controls',
        'relation' : 'Developer',
        'snippet': 'A set of First Person Shooter controls written for Three.js',
        'imageUrl': imageLocation + 'fpscontrols.png',
        'technologies': 'JavaScript, HTML, CSS',
        'demo' : "https://jamesmilneruk.github.io/threejs-fps-controls",
        'license': "https://github.com/JamesMilnerUK/threejs-fps-controls/blob/master/LICENSE",
        'github' : "https://github.com/JamesMilnerUK/threejs-fps-controls",
        'tags' : ['javascript', 'threejs','fpscontrols']},

        {'name': 'Globe Gaze',
        'relation' : 'Developer',
        'snippet': 'An experimental attempt at controlling a 3D globe using your eyes. Uses Cesium JS',
        'imageUrl': imageLocation + 'globegaze.png',
        'technologies': 'JavaScript, HTML, CSS, Cesium.js',
        'demo' : "https://jamesmilneruk.github.io/globe-gaze",
        'license': "https://github.com/JamesMilnerUK/globe-gaze/blob/master/LICENSE",
        'github' : "https://github.com/JamesMilnerUK/globe-gaze",
        'tags' : ['javascript', 'gaze', '3d', 'cesium', 'cesiumjs']},

        {'name': '10k Tiles',
        'relation' : 'Developer',
        'snippet': 'A nice set of interactive tiles built using HTML/CSS in under 10kb',
        'imageUrl': imageLocation + '10ktiles.png',
        'technologies': 'HTML, CSS',
        'demo' : "https://jamesmilneruk.github.io/10k-tiles",
        'license': "",
        'github' : "https://github.com/JamesMilnerUK/10k-tiles",
        'tags' : ['10k', 'small', 'javascript', 'css']},

        {'name': '10k Quadtree',
        'relation' : 'Developer',
        'snippet': 'A representation of a Quadtree built in HTML/CSS in under 10kb',
        'imageUrl': imageLocation + 'quadtree.png',
        'technologies': 'HTML, CSS',
        'demo' : "https://jamesmilneruk.github.io/10k-quadtree",
        'license': "",
        'github' : "https://github.com/JamesMilnerUK/10k-quadtree",
        'tags' : ['10k', 'small', 'javascript', 'css']},

        {'name': 'GitHub Map',
        'relation' : 'Developer',
        'snippet': 'A world map of GitHub users using Leaflet, scraped using Python',
        'imageUrl': imageLocation + 'githubmap.png',
        'technologies': 'Leaflet, JavaScript, Python (scrapping)',
        'demo' : "https://jamesmilneruk.github.io/github-map",
        'license': "MIT",
        'github' : "https://github.com/JamesMilnerUK/github-map",
        'tags' : ['javsascript', 'leaflet', 'map', 'github']},

        {'name': 'Labelgun',
        'relation' : 'Developer',
        'snippet': 'A library to help reduce clutter across mapping libraries',
        'imageUrl': imageLocation + 'labelgun.png',
        'technologies': 'Leaflet, JavaScript, Python (scrapping)',
        'demo' : "https://geovation.github.io/labelgun/",
        'license': "MIT",
        'github' : "https://github.com/Geovation/labelgun",
        'tags' : ['javascript', 'leaflet', 'map', 'openlayers', 'openlayers3', 'es6', 'webpack']},

        {'name': 'Facebook Population Viz',
        'relation' : 'Developer',
        'snippet': 'Visualising Facebooks population dataset on the web',
        'imageUrl': imageLocation + 'facebookviz.png',
        'technologies': 'Openlayers, JavaScript, Python, GDAL',
        'demo' : "",
        'license': "MIT",
        'github' : "https://github.com/JamesMilnerUK/facebook-pop-viz",
        'tags' : ['facebook', 'dataviz', 'data','python','gdal','geotiff','web', 'openlayers']},

        {'name': 'Tiler',
        'relation' : 'Developer',
        'snippet': 'A vector tile pipeline using Docker',
        'imageUrl': imageLocation + 'tiler.png',
        'technologies': 'Openlayers, JavaScript, Python, GDAL',
        'demo' : "",
        'license': "MIT",
        'github' : "https://github.com/Geovation/tiler",
        'tags' : ['gis', 'vector tiles', 'vector', 'tiles', 'docker']},

        {'name': 'Globe Plotter',
        'relation' : 'Developer',
        'snippet': 'Visualising global data with Go',
        'imageUrl': imageLocation + 'globeplotter.png',
        'technologies': 'Openlayers, JavaScript, Python, GDAL',
        'demo' : "https://globe-plotter.herokuapp.com",
        'license': "MIT",
        'github' : "https://github.com/JamesMilnerUK/globe-plotter",
        'tags' : ['dataviz', 'globe', 'go', 'golang', 'world', 'viz', 'visualisation', 'data', 'gis']},

        {'name': 'Scratch Map',
        'relation' : 'Developer',
        'snippet': 'A digital scratch map for documenting your travels',
        'imageUrl': imageLocation + 'scratchmap.png',
        'technologies': 'Polymer, JavaScript',
        'demo' : "https://jamesmilneruk.github.io/scratchmap",
        'license': "MIT",
        'github' : "https://github.com/JamesMilnerUK/scratchmap",
        'tags' : ['web', 'web components', 'webpack', 'es6', 'components', 'polymer', 'javascript', 'map', 'scratch', 'scratchmap', 'html', 'css']},

        {'name': 'Git Words',
        'relation' : 'Developer',
        'snippet': 'Check the occurence of words in your Git commits',
        'imageUrl': imageLocation + 'gitwords.png',
        'technologies': 'git, Go',
        'demo' : "",
        'license': "MIT",
        'github' : "https://github.com/JamesMilnerUK/git-words",
        'tags' : ['Go', 'git', 'golang', 'version control', 'commits']},


        {'name': 'Podaris Web App',
        'relation' : 'Contract Developer',
        'snippet': 'A web application for real-time collaboration transport planning',
        'imageUrl': imageLocation + 'podaris.png',
        'technologies': 'Meteor, JavaScript',
        'demo' : "",
        'license': "",
        'github' : "https://github.com/JamesMilnerUK/git-words",
        'tags' : ['meteor', 'javascript', 'html', 'css']},

        {'name': 'Flock',
        'relation' : 'Contract Developer',
        'snippet': 'Mobile application for pay-as-you-fly drone insurance',
        'imageUrl': imageLocation + 'flock.png',
        'technologies': 'JavaScript, Angular, Ionic',
        'demo' : "",
        'license': "",
        'github' : "",
        'tags' : ['javascript', 'ionic', 'nodejs', 'node', 'express']},


        {'name': '3D Repo',
        'relation' : 'Fulltime Fullstack Developer',
        'snippet': 'A collaborative online BIM platform',
        'imageUrl': imageLocation + 'flock.png',
        'technologies': 'Angular, Service Worker, Pug, Gulp, Webpack, Node.js',
        'demo' : "",
        'license': "",
        'github' : "",
        'tags' : ['javascript', 'ionic', 'nodejs', 'node', 'express']},

      ];


export default ProjectsData
